
const GEMINI_API_KEY = 'AIzaSyA2u56h76HNeokU4g9QjhYv65HoXqtW0ew';
const API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

export const explainCode = async (code: string, context: 'file' | 'function' | 'endpoint', name?: string) => {
  let prompt = '';
  
  if (context === 'file') {
    prompt = `
      You are an expert senior developer. Please explain the following code file.
      
      Structure your response as follows:
      1. **Purpose**: A brief, human-like summary of what this file does (2-3 sentences).
      2. **Key Functions**: A bulleted list of the main functions/components and their specific roles.
      3. **Logic Flow**: Briefly explain how the data or logic flows through this file.

      Keep the tone professional but easy to understand. Avoid overly technical jargon where simple terms suffice.
      
      Code:
      ${code}
    `;
  } else if (context === 'function') {
    prompt = `
      You are an expert senior developer. Please explain the function "${name}".
      
      Structure your response as follows:
      1. **Goal**: What does this function achieve?
      2. **Inputs/Outputs**: Briefly mention what it takes in and what it returns.
      3. **How it works**: A concise explanation of the internal logic.

      Code:
      ${code}
    `;
  } else if (context === 'endpoint') {
    prompt = `
      You are an expert senior developer. Please explain the API endpoint "${name}".
      
      Structure your response as follows:
      1. **Route**: What is the purpose of this endpoint?
      2. **Handling**: How does it process the request?
      3. **Response**: What kind of response does it send back?

      Code:
      ${code}
    `;
  }

  try {
    const response = await fetch(`${API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        safetySettings: [
            { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
            { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
            { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
            { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
        ]
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error?.message || `API Error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    
    if (!data.candidates || data.candidates.length === 0) {
        if (data.promptFeedback) {
             throw new Error(`Blocked by safety filters: ${JSON.stringify(data.promptFeedback)}`);
        }
        throw new Error('No explanation generated by the model.');
    }

    return data.candidates[0].content.parts[0].text;
  } catch (error: any) {
    console.error('Gemini API Error:', error);
    return `**Error generating explanation:**\n\n${error.message || 'Unknown error occurred.'}\n\nPlease check your API key and network connection.`;
  }
};
